apiVersion: apps/v1
kind: Deployment
metadata:
  name: dostainer
  labels:
    app: dostainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dostainer
  template:
    metadata:
      labels:
        app: dostainer
    spec:
      containers:
      - image: uchimata/dostainer
        imagePullPolicy: Always
        name: dos
        # Argument defines sleep time after allocating memory in s. Check with top -o %MEM
        #command: ["/app/fill-memory.sh", "6"] 
        #resources:
        #  limits:
        #    memory: "200Mi"
        #  requests:
        #    memory: "100Mi"
        # Check with df -h
        #command: ["/app/fill-disk.sh"] 
        #resources:
        #  requests:
        #    ephemeral-storage: "2Gi"
        #  limits:
        #    ephemeral-storage: "4Gi"
        command: ["/app/forkbomb.sh"] 
